Removing irrelevant example files
bitovi/bitops pull request #361
Opened 2022-11-21 20:13 UTC by PhillypHenning

# Description
Removing files and folders that contain out-of-date examples. 

Please delete options that are not relevant.

- [X] Documentation update

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation

2022-11-21 20:31 UTC, armab reviewed
Not sure about this change as there are blogs that refer to examples residing in this repo.

For example, https://www.bitovi.com/blog/devops-automation-using-stackstorm-bitops-infrastructure blog points to https://github.com/bitovi/bitops/tree/main/docs/examples/bitops+terraform+ansible+stackstorm-blog

But I'm sure there might be some examples that don't have blog references that 💯  worth removing.

@mickmcgrath13 your thoughts on that?

2022-11-21 21:48 UTC, PhillypHenning commented
That's true but it still is in the history. Perhaps we can branch + protect and make a note in the README?

2022-11-21 21:55 UTC, PhillypHenning commented
Additionally - I just went through our blogs and though yes some blogs certainly point to these. They, to my knowledge, were never really used (didn't lead to conversion) and the blogs themselves didn't do great stats wise. 

Recent stats from a quick sampling suggests it's not worth keeping these based on the blogs as they aren't really popular anyways.

2022-12-08 19:32 UTC, mickmcgrath13 requested changes
@PhillypHenning A lot of these that are being removed _would_ be valuable for future blog posts (`bitops-fast-react-static-renderer`, for example), and in the `bitops+terraform+ansible-blog` environment dir not being referenced from connor's blog?

2022-12-08 19:37 UTC, mickmcgrath13 commented
sorry, just properly caught up on the conversation in this thread.
- I don't think we should remove the ones referenced by blogs.  I'm not convinced these links in blogs are contributing to the lack of conversion, and IMO, more info is better.
- I also think we should put the ones being removed somewhere for safe-keeping.  If that's a branch, I'd say we need to have an easy-to-find link to be able to find them.  Would it make sense to move them to our internal ops repo examples repo until we can turn them into a GHA, write a blog about them, etc.?

2022-12-08 19:55 UTC, armab commented
`bitops-archive` or `bitops-examples`?

2025-08-25 17:15 UTC, closed without merging